version: '3'

services:
  'portugal-jobs':
    build: .
    volumes:
      - './.env:/app/.env'
    container_name: portugal-jobs
    restart: always
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production